export const VALID_SECTION_TYPES = new Set<string>([
  "COMPANY", "PRODUCT_CATEGORIES", "TARGET_GROUPS", "BRAND_LANGUAGE",
  "MARKETING_CONTENT", "SALES", "LEGAL_COMPLIANCE", "EXISTING_CONTENT",
  "VISUAL_GUIDELINES", "AI_RULES",
]);
